const TODO = {
    GETALL: 'TODO_GETALL',
    SHOW: 'TODO_SHOW',
    ADD: 'TODO_ADD',
    CHECK: 'TODO_CHECK',
    GET_ONE: 'TODO_GET_ONE',
    GO_TO_EDIT: 'TODO_GO_TO_EDIT',
    EDIT: 'TODO_EDIT',
    REMOVE: 'TODO_REMOVE',
    READY: 'TODO_READY',
    READY_RESET: 'TODO_READY_RESET'
}

export default TODO