const USER = {
    CHANGE_USERNAME: 'USER_CHANGE_USERNAME',
    CHANGE_EMAIL: 'USER_CHANGE_EMAIL',
    CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
    SHOW_PROFILE: 'USER_SHOW_PROFILE',
    GET_PROFILE: 'USER_GET_PROFILE'
}

export default USER